name = "star-weave-astrology"
compatibility_date = "2026-03-17"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = "./dist"

[assets]
binding = "STATIC_ASSETS"
directory = "./dist/client"

[[kv_namespaces]]
binding = "SESSION"
id = "cb3c32fa56e341ffb9a4df276d89c09e"
